import { PRODUCT_FRAGMENT } from "./productFragment.graphql";
import { PRODUCT_ITEM_FRAGMENT, PRODUCT_VARIANTS_FRAGMENT } from "./productItemFragment.graphql";
import { PRODUCT_VARIANT_FRAGMENT } from "./productVariantFragment.graphql";
import { CUSTOMER_FRAGMENT, CUSTOMER_FRAGMENT_ACCOUNT, CUSTOMER_ORDERS_FRAGMENT } from "./customerFragment.graphql"
import { MONEY_PRODUCT_ITEM_FRAGMENT } from "./MoneyProductItemFragment.graphql";
import { PRODUCT_ITEM_FRAGMENT_WITHOUT_VARIANT_FRAGMENT } from "./productItemFragment.graphql";
import { MENU_ITEM_FRAGMENT } from "./menuItemFragment.graphql";
import { ORDER_ITEM_FRAGMENT } from "./orderFragment.graphql";




export {
  PRODUCT_FRAGMENT,
  PRODUCT_ITEM_FRAGMENT,
  PRODUCT_VARIANT_FRAGMENT,
  CUSTOMER_FRAGMENT,
  MONEY_PRODUCT_ITEM_FRAGMENT,
  PRODUCT_ITEM_FRAGMENT_WITHOUT_VARIANT_FRAGMENT,
  MENU_ITEM_FRAGMENT,
  ORDER_ITEM_FRAGMENT,
  CUSTOMER_FRAGMENT_ACCOUNT,
  CUSTOMER_ORDERS_FRAGMENT,
  PRODUCT_VARIANTS_FRAGMENT,
}